name: Rohans Selenium Framework Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Rohan.Selenium.Framework/Rohan.Selenium.Framework.sln'
      NUGET_URL: 'https://nuget.pkg.github.com/rohanjasons/index.json'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with: 
        nuget-api-key: ${{secrets.ACTION_TOKEN}}
        
    - name: Add Package Source
      run: dotnet nuget add source --username rohanjasons --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github $NUGET_URL

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=1.2.$GITHUB_RUN_NUMBER 
      
    - name: Publish
      run: nuget push **\*.nupkg -Source $NUGET_URL -ApiKey ${{secrets.ACTION_TOKEN}}
